### ISSUE TITLE
Remove ugly scrollbars from the page

### ISSUE THREAD

**Issue by zsol** [zsol/py.wtf#100]
![image](https://user-images.githubusercontent.com/66740/188126782-4aa37a59-245e-491f-b84e-c891f8011629.png)

**Comment by anuj98** [comment]
Hi @abesto, I am new to contributing to open source, can I pick this issue?

**Comment by abesto** [comment]
@anuj98 All yours, thank you for giving this a go!

**Comment by anuj98** [comment]
> @anuj98 All yours, thank you for giving this a go!

I cloned the repo and have python and node installed. But couldn't run the following commands. I have a windows system. Could you please help me?

**Comment by abesto** [comment]
Please paste the full command and the full output. I don't develop on Windows, but let's see what we can find.

**Comment by anuj98** [comment]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/30874550/188282460-774452f9-8a79-4040-b10f-ea5221a88e40.png">

Not able to create YOUR_FAVOURITE_PROJECT variable on the command prompt/powershell

**Comment by zsol** [comment]
Try replacing `$YOUR_FAVORITE_PROJECT` with `click`
so the full command to run is
```sh
py-wtf index --project-name click www/public/_index
```

**Comment by abesto** [comment]
Ah yes. `A=b` is syntax that Linux/macOS shells support, but not PowerShell. As @zsol says, your life is likely to be easiest by just directly putting in the name of the project instead of using a variable here.

**Comment by anuj98** [comment]
This is the next issue:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/30874550/188282506-dc2bcfae-4cd1-4c3d-bc40-ccb27793d1ce.png">

**Comment by abesto** [comment]
That looks like you missed (or ran in another shell?) the `pipx run hatch shell` command, which would set you up with an environment where `py-wtf` is available.

If that doesn't seem to work, you can `pipx run hatch run py-wtf index` etc etc

**Comment by anuj98** [comment]
Thanks @zsol and @abesto it worked.

**Comment by anuj98** [comment]
Hi,
I feel like I might still be missing something because I am not able to see any data? I know the fix but unless the inside components don't render won't be able to verify everything is working with that fix.
<img width="891" alt="image" src="https://user-images.githubusercontent.com/30874550/188283524-7dcc5974-0d5f-429c-9422-61c1d3e90cf6.png">

**Comment by zsol** [comment]
Yeah there should be a `click.json` file that's generated by `py-wtf index --project-name click www/public/_index`. Unless! You were already in the `www` directory? In which case you can run either:
- `py-wtf index --project-name click public/_index`
- `py-wtf generate-test-index`

**Comment by anuj98** [comment]
@zsol Its not generating that file.

If I directly run `py-wtf index --project-name click public/_index` or `py-wtf generate-test-index` it gives the same error I got previously.
<img width="596" alt="image" src="https://user-images.githubusercontent.com/30874550/188284527-bf02b6b9-ccc5-4471-ada1-c12781740e85.png">

So I tried the solution `pipx run hatch run py-wtf index....` then the command runs but don't see the file created.
I'll try to find a fix but cannot guarantee anything. Do let me know if I can try anything else to fix this issue.

Thanks

**Comment by abesto** [comment]
@anuj98 Well, unless you specifically care about understanding / debugging / working on the indexer, you *could* grab the live JSONs and plop them in the right place, e.g.: https://py.wtf/_index/click.json

For debugging: what's the output of `pipx run hatch run ...`? What does `git status` say?

**Comment by zsol** [comment]
you have `py_wtf` in your command line instead of `py-wtf`

You can also try running `pipx run hatch run py-wtf generate-test-index`

**Comment by anuj98** [comment]
Raised a PR. Please take a look.
