### ISSUE TITLE
@welcome-ui/link vs react-router-dom

### ISSUE THREAD

**Issue by abesto** [zsol/py.wtf#32]
We use client-side routing for ... reasons. That means `react-router-dom`. The `Link` component of `react-router-dom` renders an `<a>` tag, and you don't get a say in this matter. However, we also use WelcomeUI; the WUI `Link` component (that we kinda need for styling / themeing) *also* renders an `<a>` tag, and you don't get a choice in THAT matter either.

Unfortunately an `<a>` tag inside another `<a>` tag is not valid, and generates a warning. It *works*, but it'd be good to not be clowny.

**Comment by anathien** [comment]
Closing this PR in favor of another approach, going back to vanilla Styled Components.

**Comment by anathien** [comment]
Woops, closed the wrong thing yesterday (issue vs PR). That said, this was solved by the alternate approach, https://github.com/zsol/py.wtf/pull/57 .
