### ISSUE TITLE
Next.JS -> Gatsby?

### ISSUE THREAD

**Issue by abesto** [zsol/py.wtf#38]
https://www.gatsbyjs.com/ uses a very similar stack to what we have now, and is explicitly designed to make building static-only sites easy. Depending on whether we foresee a world where we *want* an active server-side component, Gatsby could be a better fit for our needs.

Comparison maintained by Gatsby: https://www.gatsbyjs.com/features/jamstack/gatsby-vs-nextjs

This is *mostly* orthogonal to "do we materialize an HTML file for each symbol"; I expect to be able to use the same tricks with Gatsby that we do now with Next.JS. I also expect we'd be able to do the rewriting in the CDN config, if we moved to using a CDN.

(Which... why aren't we doing that? Fire up a free CloudFlare account, point it at GH pages, do the URL rewriting there, get the SEO benefits, drop the horrible URL rewriting hacks?)

**Comment by zsol** [comment]
I haven't done any due diligence when picking nextjs and mainly went with @anathien's suggestion to the question "what JS framework do we use this week" without any details 🤣 

I'm not familiar with Gatsby but based on their own comparison site I'm not sure what benefits would it bring _us_. I actively want to avoid a server-side component, to make ongoing maintenance (and hosting costs) lower. I don't ever want to deal with autoscaling a backend in the unlikely event of getting slashdotted.

Re: CDN - yeah that's totally the plan. Didn't realize you could do URL rewriting in CloudFlare. I'll look into it

**Comment by abesto** [comment]
> based on their own comparison site I'm not sure what benefits would it bring us

Yeah there isn't really any single big item. I expect more things along the lines of: the philosophy of the framework aligns strongly with what we want to do, so things we want to do will tend to be marginally/moderately easier than in Next.

**Comment by zsol** [comment]
I'm down if you're down, but would probably not do it myself 🙃

**Comment by abesto** [comment]
It sounds like an interesting thing to do, but also we have SO MANY BETTER THINGS to do ATM. Let's keep this in the back-pocket in case we run into any (other) Next JS limitations.
