### ISSUE TITLE
Display __all__ on module pages

### ISSUE THREAD

**Issue by abesto** [zsol/py.wtf#39]
https://github.com/zsol/py.wtf/pull/33 added explicit exports to the index; let's show them! Probably as a dedicated section near the top of the module contents page.

**Comment by zsol** [comment]
#33 is not enough, we'll need proper xrefs even for intra-linked symbols here unfortunately (as described in #8), because for this

```
from foo import bar as baz
__all__ = ["baz"]
```

We'll want to generate a link that's called `baz`, but points to the symbol `foo.bar`. Can't do that with plain strings.

**Comment by zsol** [comment]
#65 should be all that's needed from the indexer side 😄

**Comment by zsol** [comment]
Fixed by #79
