### ISSUE TITLE
Make symbols clickable

### ISSUE THREAD

**Issue by abesto** [zsol/py.wtf#4]
Wherever a type or function or class is mentioned (esp. in a code block), it should link to the documentation for that symbol.
This needs the symbols to have URLs - see #3

This is especially tricky because of generics.

**Comment by zsol** [comment]
I assume you mean the highlighting will be nontrivial in type annotations because of generics? We could have the indexer emit a bit more structured type annotations if that helps

**Comment by zsol** [comment]
This is implemented by #78
