### ISSUE TITLE
Set up CloudFlare

### ISSUE THREAD

**Issue by zsol** [zsol/py.wtf#40]
Fire up a free CloudFlare account, point it at GH pages, do the URL rewriting there, get the SEO benefits, drop the horrible URL rewriting hacks?

_Originally posted by @abesto in https://github.com/zsol/py.wtf/issues/38_

**Comment by abesto** [comment]
FWIW, testing this *should* be easy: the horrible hacks will just not be triggered if you manage to do the rewriting in CloudFlare. So no code changes needed to verify Things Work.

**Comment by zsol** [comment]
This is done. We're on the free tier in CloudFlare, so no regex matching on the URI. Let's just hope we don't generate URIs with `/_next/` or `/_index/` in them :)
