### ISSUE TITLE
Restructure content?

### ISSUE THREAD

**Issue by abesto** [zsol/py.wtf#6]
I'm pretty sure that to make content legible, each "page" / view should contain docs on exactly one top-level... thing. So for example
* A module page may contain a listing of all the top-level symbols, maybe with the first line or so of its docstring
  * Maybe variable / constant docs are just fully inlined here
* Separate pages for classes (what's up with inner classes?)
* Separate pages for top-level functions?

I don't know what plans you had in mind about all this. I've hinted at this before, but I'll just drop it here explicitly so that there's a place to discuss it: my default approach would be to model the organization structure on docs.rs. Some things obviously need adapting as the languages differ, but even so that should be much less effort than trying to design this from first principles.

**Comment by zsol** [comment]
Yep, fully mimicking rustdoc is a great baseline. In terms of content, there's probably going to be less content per class than for your average rust struct, but that's probably fine.

So I'd say yes to all your bullet points, with the exception of toplevel variable/constant docs; I'd treat those the same as functions (just get the first line of the doc).

`py.wtf/package/foo.bar` should have the full docs and signature for the `foo.bar` symbol (whether it's a module, var, func, class) and an index of all other symbols it "contains".
