### ISSUE TITLE
Link stdlib symbols to https://docs.python.org

### ISSUE THREAD

**Issue by abesto** [zsol/py.wtf#99]

**Comment by zsol** [comment]
While looking into this, I discovered the existence of https://docs.python.org/3/library/sys.html#sys.builtin_module_names and https://docs.python.org/3/library/sys.html#sys.stdlib_module_names

Funnily enough, you'd think that the former is a strict subset of the latter, but I found that to be not the case on all Python interpreters I have access to.

```python
>>> import sys
>>> set(sys.builtin_module_names) <= sys.stdlib_module_names
False
```

This helps figure out what the offenders are (i.e. compiled into the interpreter but isn't in the stdlib):

```python
import sys
[name for name in sys.builtin_module_names if name not in sys.stdlib_module_names]
```

The usual suspects are the [`_xxsubinterpreters`](https://github.com/python/cpython/blob/main/Modules/_xxsubinterpretersmodule.c) and [`xxsubtype`](https://github.com/python/cpython/blob/main/Modules/xxsubtype.c) modules. I think they're accidentally there on all Windows & Linux builds I've tested.

Fun.
